#!/usr/bin/env python3
"""Generate the RHWA operator-upgrade status page from GitHub and Prow."""

import datetime
import json
import os
import sys
import urllib.error
import urllib.request


GITHUB_API = "https://api.github.com"
PROW_BUCKET = "https://storage.googleapis.com/origin-ci-test/pr-logs/directory"
NHC_JOB = (
    "pull-ci-medik8s-node-healthcheck-operator-main-"
    "5.0-e2e-system-tests-nhc-operator-upgrade"
)
NHC_FRESH_JOB = (
    "pull-ci-medik8s-node-healthcheck-operator-main-"
    "5.0-e2e-system-tests-nhc-fresh-install"
)
NHC_PR_CLUSTER_JOB = (
    "pull-ci-medik8s-node-healthcheck-operator-main-"
    "5.0-e2e-system-tests-nhc-4-22-to-5-0-pr-bundle"
)
NHC_CLUSTER_JOB = (
    "pull-ci-medik8s-system-tests-main-4.22-to-5.0-"
    "e2e-nhc-upgrade-4-22-to-5-0-aws"
)
NHC_DOWNSTREAM_FRESH_JOB = (
    "pull-ci-medik8s-system-tests-main-5.0-"
    "e2e-nhc-downstream-fresh-install-aws"
)

OPERATORS = [
    ("NHC", "medik8s/node-healthcheck-operator", 430, "medik8s/system-tests", 113),
    ("MDR", "medik8s/machine-deletion-remediation", 191, "medik8s/system-tests", 99),
    ("SBR", "medik8s/storage-based-remediation", 95, "medik8s/system-tests", 101),
    ("NMO", "medik8s/node-maintenance-operator", 183, "medik8s/system-tests", 100),
    ("FAR", "medik8s/fence-agents-remediation", 220, None, None),
    ("SNR", None, None, None, None),
]


def request(url, *, parse_json=False):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "system-tests-wiki"}
    token = os.environ.get("GH_TOKEN")
    if token and url.startswith(GITHUB_API):
        headers["Authorization"] = f"Bearer {token}"

    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=20) as response:
            body = response.read().decode().strip()
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
        return None

    return json.loads(body) if parse_json else body


def pull_request(repo, number):
    if not repo or not number:
        return None

    return request(f"{GITHUB_API}/repos/{repo}/pulls/{number}", parse_json=True)


def pr_cell(repo, number, pr):
    if not repo or not number:
        return "Not established"

    url = f"https://github.com/{repo}/pull/{number}"
    if not pr:
        return f"[#{number}]({url}) (status unavailable)"

    state = "merged" if pr.get("merged_at") else pr.get("state", "unknown").lower()
    if pr.get("draft") and state == "open":
        state = "open draft"

    base = pr.get("base", {}).get("ref")
    suffix = f", targets `{base}`" if base else ""

    return f"[#{number}]({url}), {state}{suffix}"


def prow_result(job):
    latest = request(f"{PROW_BUCKET}/{job}/latest-build.txt")
    history = f"https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/{job}"
    if not latest:
        return "No completed run yet", history

    finished = request(f"{PROW_BUCKET}/{job}/{latest}/finished.json", parse_json=True)
    if not finished:
        return f"Build {latest}: result unavailable", history

    result = finished.get("result") or ("SUCCESS" if finished.get("passed") else "FAILURE")
    timestamp = finished.get("timestamp")
    date = datetime.datetime.fromtimestamp(timestamp, datetime.UTC).date().isoformat() if timestamp else "unknown date"

    return f"{result.title()} ({date}, build {latest})", history


def generate():
    today = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
    prs = {}
    for _, source_repo, source_number, test_repo, test_number in OPERATORS:
        prs[(source_repo, source_number)] = pull_request(source_repo, source_number)
        prs[(test_repo, test_number)] = pull_request(test_repo, test_number)

    release_pr = pull_request("openshift/release", 84788)
    prow_status, prow_history = prow_result(NHC_JOB)
    fresh_prow_status, fresh_prow_history = prow_result(NHC_FRESH_JOB)
    pr_cluster_status, pr_cluster_history = prow_result(NHC_PR_CLUSTER_JOB)
    cluster_prow_status, cluster_prow_history = prow_result(NHC_CLUSTER_JOB)
    downstream_fresh_status, downstream_fresh_history = prow_result(NHC_DOWNSTREAM_FRESH_JOB)

    lines = [
        "# RHWA OpenShift 5 operator upgrade status",
        "",
        f"Automatically refreshed: **{today}**",
        "",
        "This page is regenerated by the `system-tests` scheduled workflow. GitHub PR states and the latest durable Prow result update automatically. A green source-level upgrade does not mean the downstream customer upgrade has passed.",
        "",
        "## Representative-sample progress",
        "",
        "| Operator | Version source PR | system-tests PR | Dedicated CI | Local source upgrade | PR-candidate CI |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for name, source_repo, source_number, test_repo, test_number in OPERATORS:
        source = pr_cell(source_repo, source_number, prs[(source_repo, source_number)])
        test = pr_cell(test_repo, test_number, prs[(test_repo, test_number)])
        if name == "NHC":
            ci = pr_cell("openshift/release", 84788, release_pr)
            ci += (
                f"; [candidate Prow]({prow_history})"
                f"; [fresh-install Prow]({fresh_prow_history})"
                f"; [PR-bundle cluster-upgrade Prow]({pr_cluster_history})"
                f"; [cluster-upgrade Prow]({cluster_prow_history})"
                f"; [downstream fresh-install Prow]({downstream_fresh_history})"
            )
            local = "Passed twice on OpenShift 5.0.0-ec.5 (2026-09-09)"
            candidate = prow_status
        else:
            ci = "Not established"
            local = "Not assessed in the NHC representative sample"
            candidate = "Not run"

        lines.append(f"| {name} | {source} | {test} | {ci} | {local} | {candidate} |")

    lines.extend([
        "",
        "## Product-qualification progress",
        "",
        "These checks stay separate so upstream evidence cannot be mistaken for downstream release qualification.",
        "",
        "| Operator | Fresh source install on OpenShift 5 | Released 4.22 operator survives 4.22 → 5.0 | Public candidate catalog upgrade | Red Hat catalog upgrade | Fresh downstream install on 5.0 |",
        "| --- | --- | --- | --- | --- | --- |",
    ])
    for name, *_ in OPERATORS:
        if name == "NHC":
            fresh_install = (
                "Passed locally on OpenShift 5.0.0-ec.5 (2026-09-09); "
                f"CI: {fresh_prow_status}"
            )
            cluster_upgrade = (
                "Local old-operator survival observed; complete PR-bundle run active; "
                f"PR-bundle CI: {pr_cluster_status}"
            )
            public_upgrade = f"Implemented with public Quay catalog; CI: {cluster_prow_status}"
            downstream_upgrade = "Not run; normal Dragonfly/Konflux catalog follows later"
            downstream_fresh = downstream_fresh_status
        else:
            fresh_install = cluster_upgrade = public_upgrade = downstream_upgrade = downstream_fresh = "Not run"

        lines.append(
            f"| {name} | {fresh_install} | {cluster_upgrade} | "
            f"{public_upgrade} | {downstream_upgrade} | {downstream_fresh} |"
        )

    lines.extend([
        "",
        "## What the NHC test actually does",
        "",
        "NHC is the one representative operator. SNR is installed only as NHC's remediation dependency. The independently selectable `tier:upgrade-operator` Ginkgo test installs pinned older NHC, upgrades it in place to the PR-built candidate bundle, verifies the new version/image/pods and preserved configuration, and cleans up its resources. The separate `tier:fresh-install` test starts clean and verifies the same candidate. The destructive `tier:upgrade-cluster` test installs released NHC on OpenShift 4.22, performs the real update to 5.0, proves NHC survived unchanged, runs remediation, then either upgrades through the PR bundle or switches to a supplied catalog and runs remediation again.",
        "",
        "The local result is from the actual automated test, not a manual simulation. The final CI proof must run the dedicated job on NHC source PR #430 so Prow supplies that PR's temporary operator and bundle images.",
        "",
        "## Current blocker",
        "",
        "The representative tests and CI jobs are in open PRs. For the current pre-merge test, the full cluster-upgrade job uses Jonah's public Quay catalog, which needs no IDMS. The catalog contains NHC 5.8.0 with an explicit 0.12.1 replacement and skip range. Local catalog-backed and Prow results are still required. The normal Dragonfly/Konflux and Red Hat RHWA catalog path follows later and must be reported separately.",
        "",
    ])

    return "\n".join(lines)


if __name__ == "__main__":
    output = generate()
    if len(sys.argv) == 2:
        with open(sys.argv[1], "w", encoding="utf-8") as output_file:
            output_file.write(output)
    else:
        print(output, end="")
